### ISSUE TITLE
You comitted your .bash_history which may contain passwords

### ISSUE THREAD

**Issue by AndreasGB** [GalCohen/dotfiles#1]
Hi, you comitted your .bash_history file, which contains the following line:

https://github.com/GalCohen/dotfiles/blob/f6ace7b9ca68433cd44bda252bcf74325859ba44/.bash_history#L3218

I would recommend you get rid of that file and change your passwords if necessary.

**Comment by GalCohen** [comment]
this is harmless, but thanks for the honest feedback! definitely removing this file.
